**Experiment No. 1 (Array operation using NumPy)**

In [1]:
import numpy as np
a=np.array(42)           #0-D Array
b=np.array([1,2,3])      #1-D Arrays
c=np.array([[1,2,3],[4,5,6]])     #2-D Arrays

In [2]:
d= np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) #3-D Arrays
e=np.array((1, 2, 3, 4, 5))     #1-D Array from tuple
f= np.array([1, 2, 3, 4], ndmin=5)  #High Dimentional Array

In [3]:
#Print the array.
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print("Each item contains",a.itemsize,"bytes")

42
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
[1 2 3 4 5]
[[[[[1 2 3 4]]]]]
Each item contains 4 bytes


In [4]:
#The type of array.
print(type(a))
print(type(b))
print(type(c))
print(type(d))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [5]:
#Numbers of Dimensions.
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)
print(f.ndim)

0
1
2
3
1
5


In [6]:
#Array Indexing.
print("The value is=",c[1][2])
print("The value is=",b[0])
print("The value is=",b[-2])    #Negative Indexing
print("The value is=",c[-1][-2])

The value is= 6
The value is= 1
The value is= 2
The value is= 5


In [7]:
#Array Slicing
a=a+1;
print(a)
b=b+1
print(b)
print(a.sum())
print(a+b)
print(c[1,1:2])
print(c[0:1,1])
print(c[:,:-1])
print(d[:,:1])

43
[2 3 4]
43
[45 46 47]
[5]
[2]
[[1 2]
 [4 5]]
[[[1 2 3]]

 [[1 2 3]]]


In [8]:
#Array slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])   #1 D Array
print(arr[:4])
print(arr[2:])
print(arr[1:6:2])
print(arr[-1:-5:-2])  
arr1 = np.array([[1, 2, 3, 4, 5],             #2 D Array
                 [6, 7, 8, 9, 10]])
print(arr1[0,1:4])
print(arr1[1,1:4])

print(arr1[0:2,1:4])

print(arr1[0:2,3:6])

[1 2 3 4]
[3 4 5 6 7]
[2 4 6]
[7 5]
[2 3 4]
[7 8 9]
[[2 3 4]
 [7 8 9]]
[[ 4  5]
 [ 9 10]]


In [9]:
arr = np.array([1, 2, 3, 4])
arr1 = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)         #Checking the data type of an array.
print(arr1.dtype)


int32
<U6


In [10]:
#Converting Data Type on Existing Arrays using astype method
arr4 = np.array([1.1, 2.1, 3.1])
print(arr4.dtype)
newarr = arr4.astype('i')
print(arr4)
print(newarr)
print(newarr.dtype)

float64
[1.1 2.1 3.1]
[1 2 3]
int32


In [11]:
#Linspace
a=np.linspace(5,15,10) #prints 10 values which are evenly spaced over the given interval 5-15  
print(a)  

[ 5.          6.11111111  7.22222222  8.33333333  9.44444444 10.55555556
 11.66666667 12.77777778 13.88888889 15.        ]


In [12]:
#NumPy Array Axis
a = np.array([[1,2,30],[10,15,4]])  
print("The array:",a)  
print("The maximum elements of columns:",a.max(axis = 0))   
print("The minimum element of rows",a.min(axis = 1))  
print("The sum of all rows",a.sum(axis = 1))  

The array: [[ 1  2 30]
 [10 15  4]]
The maximum elements of columns: [10 15 30]
The minimum element of rows [1 4]
The sum of all rows [33 29]


In [13]:
#NumPy Array Axis
a = np.array([[1,2,30],[10,15,4]])  
print("The array:",a)  
print("The maximum elements of columns:",a.max(axis = 0))   
print("The minimum element of rows",a.min(axis = 1))  
print("The sum of all rows",a.sum(axis = 1))  

The array: [[ 1  2 30]
 [10 15  4]]
The maximum elements of columns: [10 15 30]
The minimum element of rows [1 4]
The sum of all rows [33 29]


In [14]:
#Arithmetic operations on the array
a = np.array([[1,2,30],[10,15,4]])  
b = np.array([[1,2,3],[12, 19, 29]])  
print("Sum of array a and b\n",a+b)  
print("Product of array a and b\n",a*b)  
print("Division of array a and b\n",a/b)   

Sum of array a and b
 [[ 2  4 33]
 [22 34 33]]
Product of array a and b
 [[  1   4  90]
 [120 285 116]]
Division of array a and b
 [[ 1.          1.         10.        ]
 [ 0.83333333  0.78947368  0.13793103]]


In [15]:
#Array Concatenation
a = np.array([[1,2,30],[10,15,4]])  
b = np.array([[1,2,3],[12, 19, 29]])  
print("Arrays vertically concatenated\n",np.vstack((a,b)));  
print("Arrays horizontally concatenated\n",np.hstack((a,b)))  

Arrays vertically concatenated
 [[ 1  2 30]
 [10 15  4]
 [ 1  2  3]
 [12 19 29]]
Arrays horizontally concatenated
 [[ 1  2 30  1  2  3]
 [10 15  4 12 19 29]]


In [16]:
#arange()
arr = np.arange(0,10,2,float)  
print(arr)

[0. 2. 4. 6. 8.]


In [17]:
#zeroes() 
array = np.zeros([2,3])  
print(array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
#ones() 
array = np.ones([2,3])  
print(array)  

[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
#identity() 
import numpy as np    
import numpy.matlib    
print(numpy.matlib.identity(4)) 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
#eye()
array = np.eye(4)  
print(array)
array = np.ones([2,3])  
print(array)  

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [21]:
#empty()
x = np.empty([3, 2])  
print(x)   

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [22]:
#ndim, ndmin.
a=np.array([['a','b','c','d','e','f']], ndmin=6)
print(a)
print('number of dimensions :', a.ndim)

[[[[[['a' 'b' 'c' 'd' 'e' 'f']]]]]]
number of dimensions : 6


In [23]:
#
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
c=np.append(a,b)
d=np.concatenate((a, b), axis=0)
print('number of concatenate :', d)
print('number of append :', c)

number of concatenate : [[1 2]
 [3 4]
 [5 6]]
number of append : [1 2 3 4 5 6]


In [24]:
#dtype in an array
arr3 = np.array([1, 2, 3, 4], dtype='i')

print(arr3)
print(arr3.dtype)

print(arr3[0])

[1 2 3 4]
int32
1


In [25]:
#shape
x = np.array([[1,2],[3,4],[5,6]])  
print("printing the original array..")  
print(x)  
x=x.reshape(2,3)  
print("printing the reshaped array..")  
print(x)

printing the original array..
[[1 2]
 [3 4]
 [5 6]]
printing the reshaped array..
[[1 2 3]
 [4 5 6]]


In [26]:
#size
x = np.array([[1,2],[3,4],[5,6]])
print(np.size(x))

6


In [27]:
#reshape
#reshape 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr.reshape(4, 3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [28]:
#reshape
#reshape 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr.reshape(2, 3, 2))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [29]:
#Sort
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [30]:
#Random
from numpy import random
x=random.randint(100, size=(5))
print(x)

[ 2 61  3 84 92]
