In [5]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Indexing
print(arr[1, 2])  # Output: 6

# Slicing
print(arr[1])  # Output: [4 5 6]
print(arr[:, 2])  # Output: [3 6 9]
print(arr[1:3, :2])  # Output: [[4 5]
                     #          [7 8]]


6
[4 5 6]
[3 6 9]
[[4 5]
 [7 8]]
