In [1]:
import numpy as np

arr = np.array([[[1, 2, 3],
                 [4, 5, 6]],

                [[7, 8, 9],
                 [10, 11, 12]]])

# Indexing
print(arr[0, 1, 0])  # Output: 4

# Slicing
print(arr[1])  # Output: [[ 7  8  9]
               #         [10 11 12]]
print(arr[0, 1])  # Output: [4 5 6]
print(arr[0, 1, 2])  # Output: 6
print(arr[:, :1, :2])  # Output: [[[ 1  2]]
                      #          [[ 7  8]]]


4
[[ 7  8  9]
 [10 11 12]]
[4 5 6]
6
[[[1 2]]

 [[7 8]]]
